apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: PGHOST
              value: db
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              value: postgres
            - name: PGDATABASE
              value: bookstore
