services:
  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "3001:3001"
    networks:
      - bookstore-net

  logic:
    build:
      context: ./logic
    container_name: logic
    ports:
      - "3002:3002"
    networks:
      - bookstore-net

networks:
  bookstore-net:
    driver: bridge
